### ISSUE TITLE
ImportError: cannot import name mss

### ISSUE THREAD

**Issue by ravenjam** [BoboTiG/python-mss#27] opened 2017-09-06 04:01 UTC
General informations:

* OS name: MacOS & Ubuntu
* OS version: MacOS Sierra & Ubuntu 16.04
* OS architecture: _64 bits_
* Result of the command `python --version`: Python 2.7.10 & Python 3.4.3

Surprised no one reported but I'm getting error:

```ImportError: cannot import name mss```

It happens on both MacOS and Ubuntu. I used:

```pip install --upgrade mss```

to install.

Any idea why?

**Comment by Tusharsb** [comment] 2017-10-05 17:19
I faced same problem as @ravenjam . It got resolved when i created a new virtual environment. My older virtual environment had some alternate screenshot grabbing packages installed - maybe they conflict with mss. My older virtual environment's `pip freeze` gave these results
```
backports.shutil-get-terminal-size==1.0.0
decorator==4.1.2
EasyProcess==0.2.3
enum34==1.1.6
ipython==5.5.0
ipython-genutils==0.2.0
line-profiler==2.0
mss==3.0.1
numpy==1.13.3
olefile==0.44
opencv-python==3.3.0.10
pathlib2==2.3.0
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.3.0
prompt-toolkit==1.0.15
ptyprocess==0.5.2
Pygments==2.2.0
pyscreenshot==0.4.2
scandir==1.6
simplegeneric==0.8.1
six==1.11.0
traitlets==4.3.2
wcwidth==0.1.7
```

Once i create a new virtual env and pip freeze gives only mss as result as follows
```
mss==3.0.1
```
*...the import problem vanishes*

**Comment by BoboTiG** [comment] 2017-11-02 09:54
I close this issue as I cannot reproduce and the module installation is fine in any cases.

**Closed by BoboTiG** 2017-11-02 09:54 UTC
