### ISSUE TITLE
PUBG Fullscreen doesn't capture as expected

### ISSUE THREAD

**Issue by andrewzwicky** [BoboTiG/python-mss#29] opened 2017-10-14 21:11 UTC
* OS name: Windows
* OS version: 8
* OS architecture: 64 bits
* Result of the command `python --version`: Python 3.6.2

### Description of the warning/error

* Run PLAYERUNKNOWN'S BATTLEGROUNDS game (PUBG) in Fullscreen mode. 
* Try to capture monitor output

### Actual output

* Output shows whatever is displayed behind game.

### Expected output

* Output will show game.

### Other details

* Fullscreen (Windowed) works as expected.
* Reference: https://github.com/andrewzwicky/PUBGIS/issues/41 as well for screenshots

**Comment by BoboTiG** [comment] 2017-11-02 09:57
Hello,
It seems related to #28. I have no time now but will try to investigate soom.

**Comment by BoboTiG** [comment] 2018-01-02 08:37
Hello,

Could you try with the [fix-windows-all-windows-not-included](https://github.com/BoboTiG/python-mss/tree/fix-windows-all-windows-not-included) branch? I  hope that fix will help with your case.

**Comment by andrewzwicky** [comment] 2018-01-04 02:02
Just tested it, still present.  Behavior seems to be the same between both versions.

**Comment by BoboTiG** [comment] 2018-05-09 15:50
Hello,

I just close this one as duplicate of #28. So far we did not found any solution, and any help is welcome :)

**Closed by BoboTiG** 2018-05-09 15:50 UTC
Labels: duplicate
